package org.example.ServerSemestr5.Enum;

public enum RequestType {
    LOGIN,
    REGISTRATION,
    GET_SCHOLARSHIP,
    SET_SCHOLARSHIP,
    GET_USERS,
    ADD_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_FACULTIES,
    ADD_FACULTY,
    UPDATE_FACULTY,
    DELETE_FACULTY,

    GET_SUBJECTS,
    ADD_SUBJECT,
    UPDATE_SUBJECT,
    DELETE_SUBJECT,

    GET_GROUPS,
    ADD_GROUP,
    UPDATE_GROUP,
    DELETE_GROUP,
    UPDATE_EXAM,
    GET_STUDENTS,
    ADD_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,
}
